### ISSUE TITLE
 vl_compilenn Error using toolboxdir 

### ISSUE THREAD

**Issue by ybeb545** [vlfeat/matconvnet#1114]
When I run vl_compilenn on matlab, I received that error:

Error using toolboxdir (line 59)
Could not locate the base directory for distcomp.

Error in vl_compilenn (line 367)
  sprintf('-I"%s"',fullfile(toolboxdir('distcomp'),'gpu','extern','include')), ...

**Comment by crvogt** [comment]
Same here, did you come across a solution?

**Comment by jotaf98** [comment]
Hi, this is because the Parallel Computing Toolbox is required. So your best bet is to install it; without it, you can't use GPU arrays. As a workaround (not sure how helpful), the "matconvnet/matlab/compatibility/parallel/" folder can be added to the path, as this contains a reimplementation of some of this toolbox's functions (though only CPU mode will be available).

**Comment by ybeb545** [comment]
Installing Parallel Computing Toolbox solved the problem, thanks jotaf98.

**Comment by KellyYutongHe** [comment]
change line 367 into
sprintf('-I"%s"',fullfile('compatibility/parallel/','gpu','extern','include')), ...
worked, thanks jotaf98

**Comment by zjuxwg0401** [comment]
change line 367 into
sprintf('-I"%s"',fullfile('compatibility/parallel/','gpu','extern','include')), ...
worked, thanks jotaf98 and KellyYutongHe

**Comment by Meskaz** [comment]
vl_compilenn
Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in vl_compilenn (line 365)
flags.nvcc = {'-D_FORCE_INLINES', '--std=c++11', ...
 

this is the error i get after changing 367 line. Please help

**Comment by jotaf98** [comment]
Hi, the use of vertcat here doesn't make any sense. If anything, concatenating strings should be horizontal concatenation. Look out for ";" vs "," mistakenly introduced (for an explanation see docs on horizontal and vertical concatenation operators)..

**Comment by Farisya33** [comment]
May I ask if there is no problem with MatConvNet beta25. Because I fail to compule the vl_compilenn in matlab.

Note: Im using matlabR2019b, visual studio 2017, CPU mode, MatConvNet 25

The error:

mt : general error c101008d: Failed to write the updated manifest to the resource of file
"C:\Users\User\AppData\Roaming\MathWorks\MATLAB_Add-Ons\Collections\vlfeat_matconvnet\vlfeat-matconvnet-1e5ae7b\matlab\mex\vl_nnconvt.mexw64".
The operation failed.

Error in vl_compilenn>mex_link (line 627)
mex(args{:}) ;

Error in vl_compilenn (line 500)
  mex_link(opts, objs, flags.mex_dir, flags) ;

Error in Test (line 8)
    vl_compilenn('EnableImreadJpeg', false);

**Comment by jotaf98** [comment]
This seems like a strange installation directory for MatConvNet. Did you put it there on purpose or is Matlab managing the paths / interpreting it as an "app" somehow?

**Comment by Farisya33** [comment]
Thank you, I can compile already after I turned off my antivirus.

But may I know how to use my jpeg images as my database in matconvnet? Because I want to train them and recognize them as a speciifc image ny using matconvnet. Somehow, I havent found yet how to convert them into something that can be read in matlab. The examples given in internet are only the trained images. Do I need to convert my jpeg images into something first? Im sorry I didnt have basic in programming
