### ISSUE TITLE
Problem compiling in RedHat-Matlab 13b - Cuda 5.0/6.5 - dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by GilLevi** [vlfeat/matconvnet#116]
Hi,

I'm trying to compile MatConvNet on Redhat. I'm using Matlab 2013b and I tried both with Cuda 5.0 and Cuda 6.5. I'm not using CuDnn for now. 

I'm running the following command to compile:

vl_compilenn('enableGpu', true,'cudaRoot','/usr/local/cuda-6.5')

And I'm getting the following error:

Error using  * 
BLAS loading error:
dlopen: cannot load any more object with static TLS

Error in vl_compilenn>mex_cuda_config (line 446)
mver = [1e4 1e2 1] * sscanf(version, '%d.%d.%d') ;

Error in vl_compilenn (line 322)
  flags.mexcu(end+1:end+2) = {'-f' mex_cuda_config(root)} ;

I googled it and it seems to be a known bug in Matlab, but I couldn't find any easy patch. Also, I don't have root privileges on this machine (but even a solution that requires root privileges would do for now).

Has anyone encountered this issue?

Thanks!
Gil.

**Comment by lenck** [comment]
Hmm, this seems to be an issue of the limited number of TLS slots addressed e.g. on [this SO problem](http://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls). You may try some of their solutions, hopefully that would help. But without a root there is little you can do... :/

Sorry that it took so long to respond. I guess you might have solved the issue since.
