### ISSUE TITLE
Why no more updates?

### ISSUE THREAD

**Issue by musicrainie** [vlfeat/matconvnet#1232]

**Comment by JingHandan** [comment]
Why stop updating？ what happened？

**Comment by jotaf98** [comment]
Hi, the most recent development happened under [AutoNN](https://github.com/vlfeat/autonn), an autodiff engine that builds on MatConvNet. This was supposed to be merged into MCN, but as it represents a significant API change (for the best IMO :) ) we decided to keep them separate. This may contribute to the impression that MCN didn't get updated for a while. So if you're looking for more capabilities, AutoNN is probably the place to look.

With that said, it is true that development has slowed as most of the devs moved on to other roles.

In that sense, help is appreciated -- if you fix a bug, with minimal changes to current code, please submit it as a PR and name me (@jotaf98) so that I get an e-mail notification.

I also ask that you confirm that you've run the full test suit on a GPU-enabled machine (`matlab/xtest/vl_testnn.m`), to ensure we don't inadvertently introduce more bugs.

**Comment by JingHandan** [comment]
> Hi, the most recent development happened under [AutoNN](https://github.com/vlfeat/autonn), an autodiff engine that builds on MatConvNet. This was supposed to be merged into MCN, but as it represents a significant API change (for the best IMO :) ) we decided to keep them separate. This may contribute to the impression that MCN didn't get updated for a while. So if you're looking for more capabilities, AutoNN is probably the place to look.
> 
> With that said, it is true that development has slowed as most of the devs moved on to other roles.
> 
> In that sense, help is appreciated -- if you fix a bug, with minimal changes to current code, please submit it as a PR and name me (@jotaf98) so that I get an e-mail notification.
> 
> I also ask that you confirm that you've run the full test suit on a GPU-enabled machine (`matlab/xtest/vl_testnn.m`), to ensure we don't inadvertently introduce more bugs.

Thanks a lot!
