### ISSUE TITLE
error for cnn_mnist.m with one gpu (v1.0-beta11)

### ISSUE THREAD

**Issue by pengsun** [vlfeat/matconvnet#139]
Hi,

The following error shows up when running `cnn_mnist.m` with one gpu. 

training: epoch 01: batch   1/600: Error using gpuArray/subsref
The data no longer exists on the device.

Error in cnn_mnist>getBatch (line 51)
im = imdb.images.data(:,:,:,batch) ;

Error in cnn_train>process_epoch (line 259)
    [im, labels] = getBatch(imdb, batch) ;

Error in cnn_train (line 146)
    [net,stats.train] = process_epoch(opts, getBatch, epoch, train, learningRate, imdb, net)
    ;

Error in cnn_mnist (line 44)
[net, info] = cnn_train(net, imdb, @getBatch, ...

The problem could be the line 90 of `cnn_train.m` :
``` Matlab
...
elseif numGpus == 1
  gpuDevice(opts.gpus)
end
...
```
which clears gpu memory so that `imdb.images.data` is not valid any more.

P.S., personally I think the previous `cnn_train.m` for single gpu should be preserved, or the new `cnn_train.m` could be a gateway function which calls the single gpu version if this is the case and no `spmd` stuff gets involved.

**Comment by vedaldi** [comment]
Hi, the problem is that the new cnn_train.m will set the current GPU as part of the initialisation. If you loaded the MNIST data in GPU memory before calling cnn_train.m, that instruction will effectively invalidate it.

Try removing these lines 

% Take the mean out and make GPU if needed
if numel(opts.train.gpus) == 1
  imdb.images.data = gpuArray(imdb.images.data) ;
end

from cnn_mnist.m
> training: epoch 01: batch 1/600: Error using gpuArray/subsref
> The data no longer exists on the device.
> 
> Error in cnn_mnist>getBatch (line 51)
> im = imdb.images.data(:,:,:,batch) ;
> 
> Error in cnn_train>process_epoch (line 259)
> [im, labels] = getBatch(imdb, batch) ;
> 
> Error in cnn_train (line 146)
> [net,stats.train] = process_epoch(opts, getBatch, epoch, train, learningRate, imdb, net)
> ;
> 
> Error in cnn_mnist (line 44)
> [net, info] = cnn_train(net, imdb, @getBatch, ...
> 
> The problem could be the line 90 of cnn_train.m :
> 
> ...
> elseif numGpus == 1
>   gpuDevice(opts.gpus)
> end
> ...
> which clears gpu memory so that imdb.images.data is not valid any more.
> 
> P.S., personally I think the previous cnn_train.m for single gpu should be preserved, or the new cnn_train.m could be a gateway function which calls the single gpu version if this is the case and no spmd stuff gets involved.
> 

While the previous version is somewhat simpler, when using a single GPU spmd should be bypassed altogether. The new version has many more features not supported by the old one (e.g. sub-batches, customisable error functions). It has better code reuse too.

We will try to clean up the code further down the line.

**Comment by pengsun** [comment]
Thanks @vedaldi :-)

**Comment by jizhihang** [comment]
@vedaldi  exercise4.m has the similary problem when I use GPU to train the net. I set the parameter "trainOpts.gpus =[1];"
the error as:
Error using gpuArray/subsref
The data no longer exists on the device.

Error in exercise4>getBatch (line 135)
im = imdb.images.data(:,:,batch) ;

Error in cnn_train>processEpoch (line 325)
    [im, labels] = params.getBatch(params.imdb, batch) ;

Error in cnn_train (line 150)
    [net, state] = processEpoch(net, state, params, 'train') ;

Error in exercise4 (line 58)
[net,info] = cnn_train(net, imdb, @getBatch, trainOpts) ;

as my analysis, the code " prepareGPUs(opts, epoch == start+1) ;" in the cnn_train.m will clear the data in the GPU.
How to correct it? THANKS!
