### ISSUE TITLE
The question about  : vl_nnconv.cpp

### ISSUE THREAD

**Issue by mingtop** [vlfeat/matconvnet#168]
----vl_nnconv.cpp 
#if ENABLE_GPU
#error This file should not be compiled with GPU support enabled
#endif
#include "vl_nnconv.cu"

---------------------------------
We can see the implements of CPU, The vl_nnconv also complie by vl_nnconv.cu . 

--------some lines ---------
--------some lines ---------
--------some lines ---------

---- vl_nnconv.m
vl_nnconv.m  are all annotation, hasn't code implement. 

I have a question here:
1. The vl_nnconv.m is implement by vl_nnconv.cu ?  This cpu edition hasn't implements by matlab function?  I want a implements of matlab implement.
2. What's the differents between   vl_nnconv.cu and /impl/nnconv.cu ?

**Comment by mingtop** [comment]
Why? 
Is any one here ?  @vedaldi 
If this project goes on like this, I think it will be died! 

I used lask week read throught the codes, it really take a lot of time of yours.  I very appreciate yours job！

**Comment by vedaldi** [comment]
Hi, it takes a very long time to keep track of all the questions on the Git repo. The project is most definitely not dead (we will release updates very soon).

Concerning your question

- there is no MATLAB-only implementation of convolution

- the implementation has several layers of abstraction. vl_nnconv.cu is the MEX driver (read more about MEX  online), which in turn will call a function defined in impl/nnconv.cu. The reason is that in this manner it will be possible to detach MatConvNet from MATLAB in the future

> On 16 Jun 2015, at 03:55, Yan Ming <notifications@github.com> wrote:
> 
> Why? 
> Is any one here ? @vedaldi <https://github.com/vedaldi> 
> If this project goes on like this, I think it will be died!
> 
> I used lask week read throught the codes, it really take a lot of time of yours. I very appreciate yours job！
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/vlfeat/matconvnet/issues/168#issuecomment-112266499>.
> 

----vl_nnconv.cpp 
#if ENABLE_GPU
#error This file should not be compiled with GPU support enabled
#endif
#include "vl_nnconv.cu"

We can see the implements of CPU, The vl_nnconv also complie by vl_nnconv.cu . 

--------some lines ---------
--------some lines ---------
--------some lines ---------

---- vl_nnconv.m
vl_nnconv.m are all annotation, hasn't code implement. 

I have a question here:
1. The vl_nnconv.m is implement by vl_nnconv.cu ? This cpu edition hasn't implements by matlab function? I want a implements of matlab implement.
2. What's the differents between vl_nnconv.cu and /impl/nnconv.cu ?
