### ISSUE TITLE
Numerical reproducibility

### ISSUE THREAD

**Issue by cytsai** [vlfeat/matconvnet#24]
First of all, this library is really awesome. Kudos to you guys!

One weird issue I just found about numerical reproducibility: the GPU-mode backward pass in certain networks (more specifically, caffe-ref/-alex and vgg-f/-m) produces slightly different gradients (at least in the bottom-most input layers) every time it runs, but is fine in other networks (e.g. vgg-s and verydeep-16/-19). The GPU-mode forward pass, as well as the CPU-mode forward and backward passes, on the other hand, is fine in all networks. Any idea what may cause this? I'm using GTX Titan and Matlab R2014b with matconvnet compiled against CUDA 6.5 here.

Thanks a lot!

**Comment by vedaldi** [comment]
Sorry for the late reply. I believe that this is the expected behaviour when running on GPU. This is due to the fact that the different GPU threads can complete at slightly different times every time, effectively changing the order of summations etc. While this is ideally irrelevant (e.g. summations are commutative and associative) in practice it will give slightly different numerical results. 

This does not affect all the algorithms. For instance CuBLAS seems to be ok:

* http://docs.nvidia.com/cuda/cublas/#cublasApi_reproducibility

However, the new CuDNN is not always reproducible according to their manual (MatConvNet now optionally uses that). In MatConvNet's case, there can be some kernels that are not reproducible. I think one of them is the backward pooling layer. MATLAB may have others non-reproducible kernels that are implicitly used by the toolbox.

While annoying, it should not really cause any serious practical issue.

**Comment by cytsai** [comment]
Hi @vedaldi, thanks a lot for getting back on this. I would guess this is the only reason too since I didn't see any stochasticity in the code either, but I do wonder if there's any known method to force nvcc to generate binaries that fully honor reproducibility. The only reason why I'm asking is because my [recent project](http://coxlab.github.io/ostrichinator/) on discovering adversarial examples using MatConvNet can potentially benefit from this (since subtle differences in backprop gradients do give rise to drastically different results from time to time), but like you mentioned, this in practice affects nearly nothing, and certainly in no way makes this a less awesome library. Kudos to you guys again.

**Comment by vedaldi** [comment]
Hi, unfortunately I am not aware of such a flag, but there must be ways of doing it at the cost of speed. However, I am afraid that it would require recoding some algorithms!
