### ISSUE TITLE
vl_imreadjpeg runs extremely slow suddenly

### ISSUE THREAD

**Issue by gclong** [vlfeat/matconvnet#242]
Hi Guys, 

I found an interesting thing when run MatConvNet's examples/**cnn_imagenet.m**:

the running time of *vl_imreadjpeg* becomes extremely slow suddenly during running.

Does anyone of you have ever suffered from this?

Figure 1: r_time in *cnn_imagenet_get_batch.m* is showed in the next figure.

![cnn_imagenet_get_batch](https://cloud.githubusercontent.com/assets/11793174/9269408/b0b422e8-42ac-11e5-90c9-db6d19244ddc.jpg)

Figure 2:  *r_time* is showed within the "(r: *r_time*)". Please note that *r_time* becomes from 0.22s to 6.89s in line of "epoch 01: batch  66/5005". 

![matlab_info](https://cloud.githubusercontent.com/assets/11793174/9269420/d29bdb6c-42ac-11e5-8e33-48069fc36b29.jpg)

Setup:
K40c GPU + 32GB RAM + Windows 7 + Matlab 2015a + cuDNN
The training data has been prepossessed by preprocess-imagenet.sh

**Comment by vedaldi** [comment]
Hi, are you running this in Windows?

**Comment by gucan-long** [comment]
Hi vedaldi,

Thanks for your wonderful work.

Yes, I am running in Windows.

**Comment by gucan-long** [comment]
Hi,

I noticed just a minutes ago, the problem might not due to the im_imreadjpeg. When I replace it with matlab-inbuilt imread(). The time for loading images also become long suddenly after some batch running.

**Comment by vedaldi** [comment]
Hi, ok. This is quite unexpected. Is it possible that the OS is simply caching in RAM some of the files?

In general, for best performance we keep image files in RAM (yes, you would need to have hundred of GBs of RAM for that) or at least in SSDs.

**Comment by gucan-long** [comment]
Hi vedaldi, thanks for your reply. 

Yes, we are planing to add new RAM chips or SSD. However, I was wondering if there are something wrong with the code itself. 

And I understand that you might be mainly working in Linux based OSs. We also plan to move into Ubuntu. However, we are constrained within Windows 7 at least for these days, which is one of the reasons why we are working with your wonderful MatConvNet.

I will update the status if there are some new findings.

Thanks for your wonderful work again.

**Comment by nicjac** [comment]
I work on Windows and I do not encounter such a dramatic slow down of the learning process. If you are using "vl_imreadjpeg", you might encounter the memory leak that was discussed in a previous issue (and fixed in the dev branch, see issue #191). 

One cause could be saturation of the RAM, leading to heavy reliance on the page file and slowing down the whole thing. Have you tried with a much smaller batch size (e.g. 10)? Also, have you tried disabling cuDNN?

**Comment by gucan-long** [comment]
Hi nicjac, thanks for your experiences. I noticed the issue #191. However, my problem might not be due to the memory leaking. BTW, by "fixed in the dev branch", do you mean that the memory leaking has been fixed in the newest beta13 version? I am currently running with beta13.

The page file problem seems not be possible as well, since I already turn off the whole virtual memory files, considering that my RAM is 32GB which might be large enough for training vgg-f CNN.

I will try your suggestions about smaller batch size and disabling cuDNN, and will report the results.

**Comment by SliMM** [comment]
Hi @gucan-long, just to let you know there is a similar drop in performance on my Mac OS and Linux as well and it's probably just the OS caching files you've opened before. 

The only way to speed things up a bit if you don't have enough RAM to keep everything there is to make sure you prefetch images (`vl_imreadjpeg` can do this for you) while you're processing a batch.

**Comment by gclong** [comment]
please refer to https://github.com/vlfeat/matconvnet/issues/187#issuecomment-150091121
