### ISSUE TITLE
error message with CUDA 6.5 and ubuntu 14.04

### ISSUE THREAD

**Issue by bittnt** [vlfeat/matconvnet#28]
Hi,
I have tried to compile the matconvnet with latest cuda 6.5, but it shows the error message:
g++: error: /usr/local/MATLAB/R2014b/bin/glnxa64/libcudart.so.6.5: No such file or directory

I found the place where we have this is in a xml file:
/matconvnet/matlab/src/config/mex_CUDA_glnxa64.sh
/matconvnet/matlab/src/config/mex_CUDA_glnxa64.xml

So I assume we need to update these files first.

Then I need to ln -s the corresponding lib files into the matlab that path. But I think these should not be the best solution, is any way to solve this?

**Comment by urimerhav** [comment]
Thanks for your help @bittnt

**Comment by lenck** [comment]
Hi, @urimerhav, your issue was probably wrong architecture settings in the variable `NVCCFLAGS`... 
In the new relase, the script `vl_compilenn` implements a new compilation method which uses `nvcc` directly, so as a side-effect it allows to use newer versions of CUDA toolkit without the need to edit the mex settings files...
You can run it with:
```
vl_compilenn('enableGpu', true, 'CudaMethod', 'nvcc')
```
And then you can also directly change the demanded CUDA architecture settings with the parameter 'cudaArch' (for example when you would have multiple cards with different compute capabilities...).
It's just info what have changed recently, if somebody would have a similar issue :)

**Comment by urimerhav** [comment]
@lenck 

Thanks a lot for your feedback. I'm afraid I already booted an Ubuntu 12 server which is Cuda 6.0 compatible, so I can't attest that it works. But it sounds good!

Best,
Uri

**Comment by vedaldi** [comment]
This is hopefully not a problem anymore in MATLAB 2014a. I managed to hack a version of the XML config file that should work regardless of the version and bundled that in the library. Also, the new vl_compilenn command with the 'cudaMethod','nvcc' should work without using this file at all.
