### ISSUE TITLE
report the error for the binary classification

### ISSUE THREAD

**Issue by swangb** [vlfeat/matconvnet#281]
For the beta15 

There is a typo in cnn_train_binary line 104.

 % setup error calculation function
if isstr(opts.errorFunction)
  switch opts.errorFunction
    case 'none'
      opts.errorFunction = @error_none ;
    case 'multiclass'
      opts.errorFunction = @error_multiclass ;
      if isempty(opts.errorLabels), opts.errorLabels = {'top1e', 'top5e'} ; end
    case 'binary'
      opts.errorFunction = @error_binaryclass ;
      if isempty(opts.errorLabels), opts.errorLabels = {'bine'} ; end
    otherwise
      error('Uknown error function ''%s''', opts.errorFunction) ;
  end
end

opts.errorFunction = @error_binary; 

should changes to

opts.errorFunction = @error_binaryclass ;

However correcting it still resulting the strange output......

Now let's make some modification to the error_binaryclass function
% -------------------------------------------------------------------------
function err = error_binaryclass(opts, labels, res)
% -------------------------------------------------------------------------
predictions = gather(res(end-1).x) ;
predictions = vl_nnsoftmax(predictions);
pred_temp = ones(size(labels));
for ii=1:size(predictions,4)
    if predictions(1,1,1,ii)<predictions(1,1,2,ii)
        pred_temp (ii) = pred_temp (ii) +1;
    end
end
error = length(find (pred_temp~=labels));
%error = bsxfun(@times, predictions, labels) < 0 ;
err = sum(error(:)) ;

For my observation, the result is reasonable. 
Do you agree with me?

**Comment by jmontoyaz** [comment]
Hi swangb,

To me looks also like that the **opts.errorFunction** should reference the **error_binaryclass** function, i.e., as mentioned by you:
**opts.errorFunction = @error_binaryclass ;**

However, the line **error = bsxfun(@times, predictions, labels) < 0;** looks correct to me,  but you need to warranty that your binary labels are: -1/+1. So that whenever your predictions match your ground-truth (**true positives/true negatives**) the result of the multiplication is also positive, for the other cases is negative (**false positives/false negatives**). Make sense?
However, I don't see any normalization by the amount of trained images so as to obtain probabilities.
What do you guys think?
