### ISSUE TITLE
is   vl_imreadjpeg() get the right image ?

### ISSUE THREAD

**Issue by taopanpan** [vlfeat/matconvnet#286]
when I  run this program in windows, get a strange result, it show the vl_imreadjpeg() get the image 
 with a single value , seems like matlab's imread() function convert the uint8 to single . is there any problem?

a{1} = which('peppers.png') ;
% load and preprocess an image
im = imread(a{1}) ;
%im = single(im);
figure(1) ; imshow(im) ;
im_= vl_imreadjpeg(a) ;
im_ = im_{1,1};
figure(2) ;  imshow(im_) ;

**Comment by vedaldi** [comment]
It is probably fine. `vl_imreadjpeg` reads the image in a single precision array in the range [0,255]. MATLAB by default wants range [0,1]. Try imshow(im_/255).

BTW, this is done because 99% of the CNN take that as an input range, so it saves rescaling the image.

**Comment by nicjac** [comment]
@vedaldi : I always wondered whether it would be possible to have "vl_imreadjpeg" work with other data types? I have 16-bit images, and would love to use it to efficiently load my data during training. Instead I have to rely on MATLAB's "imread", which is much much slower and does not offer the pre-fetching capabilities of "vl_imreadjpeg".

**Comment by vedaldi** [comment]
Hi, well, yes, it would be possible, except for the fact that most CNNs would take single() anyways?

Ideally, we would like to add image transformations and maybe even transferring of the batch to GPU, but I am a bit hesitant in adding further complexity.

**Comment by nicjac** [comment]
I understand that but myself and people in my field (X-ray imaging) routinely use 16-bit (or higher) images. If saved as 8-bit, there will be a significant loss of precision (and we actually showed that it impacts the performance of our trained CNNs). I know that for most applications with photographic images this is not needed, but CNNs are getting very popular in fields working with scientific images, which are very rarely 8-bit.

Does it make sense?

The argument for simplicity is a good one though. I might just write my own custom version of "vl_imreadjpeg" to fit my needs as it is probably still a niche case.

**Comment by vedaldi** [comment]
Hi, ok, this is clearer. It is an interesting thought as we will also be working on some medical applications and I did not expect this to be a potential issue.

In Windows and Mac, vl_imreadjpeg should in fact read pretty much any file format, as it relies on the general-purpose libraries that ship with the OS. However, I think that the code would have to be changed slightly to take advantage of 16bit spaces (when converting to single precision). This should be easy.

On linux, we would have to add explicit support for PNG, unless we can find a widely-distributed general-purpose image library to piggy-back on as we do in Windows and Mac OS X.

**Comment by nicjac** [comment]
@vedaldi , could you point me to the piece of code that does this conversion (imread_helpers?) I can't get vl_imreadjpeg to output anything else than a 8-bit image regardless of what I try (on Windows).

**Comment by vedaldi** [comment]
Hi,

sure. In windows the key file is `matlab/src/bits/impl/imread_gdiplus.cpp` (gdiplus being a Windows library).

If you look at the method `ImageReader::imply::read()` in the immured_gdiplus.cpp file, you will see how this works.

The key for you would be to change the target pixel format from `PixelFormat32bppRGB` into something that supports the desired precision (I guess `PixelFormat48bppRGB` or `PixelFormat64bppARGB` or `PixelFormat64bppPARGB` see here https://msdn.microsoft.com/en-us/library/windows/desktop/ms534412(v=vs.85).aspx) <https://msdn.microsoft.com/en-us/library/windows/desktop/ms534412(v=vs.85).aspx)>  

To support this properly, you should do this only if you want 16 bit resolution (and if the file is 16 bit), which should be detected when the image format is read (it would otherwise still probably work, but it would be very slow). But if you want to hack a quick version, you can simply hardcode the 16 bit version.

The most annoying part is that then you would have to convert this back to single in MATLAB format, which means transposing width and height *and* splitting colours into different channels. This is what the code in `imread_hepers.hpp` does. Here you can go “hardcore” and write SSE optimised code or do a for loop.

Andrea

**Comment by iTomxy** [comment]
I got this error in my docker, too... To enable `vl_imreadjpeg` for fast reading, the simplest way I found currently is to convert them to real jpeg files with the OpenCV lib in python, *i.e.* read those non-jpeg files with `cv2` and re-save them in `.jpg` format.

A simple demo code:
```python
import os.path as osp
import cv2
from PIL import Image


P = "/home/dataset/flickr"
IMAGE_P = osp.join(P, "mirflickr")
REAL_JPEG_P = osp.join(P, "real_jpeg")

non_jpeg = [608, 611, 692, 705, 733, 737, 798]
for _id in non_jpeg:
    # print("---", _id, "---")
    img_name = "im{}.jpg".format(_id)
    img_p = osp.join(IMAGE_P, img_name)

    # read image
    img = cv2.imread(img_p)
    if img is None:  # cv2 failed -> use PIL.Image
        img_f = Image.open(img_p)
        img = np.asarray(img_f)
        img_f.close()
        if 2 == img.ndim:  # lack channel
            img = np.repeat(img[:, :, np.newaxis], 3, axis=2)

        # has to convert the channel order if read with `PIL.Image`
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    # re-save the image
    cv2.imwrite(osp.join(REAL_JPEG_P, img_name), img)
```
