### ISSUE TITLE
Adapt CNN for 4 channels.

### ISSUE THREAD

**Issue by as3nsi0** [vlfeat/matconvnet#320]
Hello,
My question is how to adapt one CNN, for example AlexNet. My idea is introduce one image in neural network with 4 channels (R,G,B and one channel of IR image), that is possible? 

Thanks for advance.

**Comment by bazilas** [comment]
hi,

In general, you can build any configuration with 4-channel input. You only have to adapt your first convolution-filters so that they take 4 channels as input.

If you would like to see how AlexNet performs on IR data, you could replicate the IR image to form 3 channel input and feed it to the network. It is not directly possible to refine AlexNet with RGB and IR (4 channels).

**Comment by as3nsi0** [comment]
Thanks for the quickly response @bazilas.
