### ISSUE TITLE
Spelling mistake in cnn_train_dag

### ISSUE THREAD

**Issue by nightrome** [vlfeat/matconvnet#322]
Hi,

in cnn_train_dag it says
sate.momentum = ...;
instead of
state.momentum = ...;
. ( https://github.com/vlfeat/matconvnet/blob/master/examples/cnn_train_dag.m#L138 )
I suppose this is a misspelling that should be corrected, right?

Cheers

**Comment by tinalegre** [comment]
@nightrome yes, it seems to be it's a "typo". In addition, I was thinking the signature of the **cnn_train_dag** function shall be changed, from:
```
function stats = cnn_train_dag(net, imdb, getBatch, varargin)
```
to:
```
function [net, stats] = cnn_train_dag(net, imdb, getBatch, varargin)
```
Note that the **net** variable has been added as output, otherwise it would not be possible to store any trained models afterwards. What do you think, or did I miss something? 
@vedaldi any lights on those two issues?
