### ISSUE TITLE
CNN predicting only one value

### ISSUE THREAD

**Issue by shivghai** [vlfeat/matconvnet#352]
I am trying to make a network to perform image verification, but for some reason the CNN only ever predicts one class, out of two classes. My input has 2 channels, the first being the first image (128x128 image) and the second being the second image (128x128). I am expecting an output of either 1 (for a match), or 2 (for non-match). My last two layers in the CNN are

net.layers{end+1} = struct('type', 'conv', ...
     'weights', {{0.01 * randn(1,1,256,2, 'single'), ...
     0.01 * randn(1,2, 'single')}}, ...
     'stride', 1, ...
     'pad', 0);

net.layers{end+1} = struct('type', 'softmaxloss');

I am using the simplenn wrapper, as well as a modified cnn_train example. To make the cnn_train example work with 2 classes, I have removed the top-5 error.

To reiterate, the issue is that my network either predicts all 1s or all 2s. Is there something else which I could be missing? I can provide more information if required

**Comment by lenck** [comment]
Hi, in those cases it always seemed to me that what is important is to properly balance the data so that the network does not end up learning just the priors. Also check if your network has not imploded during training (setting layer filters to zeros) because then it can just realise the priors with the biases...
What you may find useful for this task is also probably this [paper](http://imagine.enpc.fr/~zagoruys/deepcompare.html)...
