### ISSUE TITLE
Does MatConvNet support fine-tuning using pre-trained model?

### ISSUE THREAD

**Issue by zwx8981** [vlfeat/matconvnet#366]
Whether or not? How? Which function?

**Comment by lenck** [comment]
Yes, of course... Just modify your network (by re-initializing the classification layer, for example) and call the `cnn_train` with your own `get_batch` function which would serve it your data... For example, you can start by modifying the `examples/imagenet/cnn_imagenet.m` where instead of initialising the new network, you would load it from a file.
Hopefully we will prepare some more examples and tutorials in the next version...

**Comment by tinalegre** [comment]
@zwx8981 of course! Have a look [here](https://github.com/vlfeat/matconvnet/issues/218) ;-)

**Comment by lenck** [comment]
@tinalegre thanks for spotting a relevant issue! :)
Duplicate to #218
