### ISSUE TITLE
How to training a model for classifying people with the VGG-Face?

### ISSUE THREAD

**Issue by apprisi** [vlfeat/matconvnet#382]
The script examples/cnn_vgg_face.m is an example of using VGG-Face for classification.But how to using other dataset? 
Thanks.

**Comment by vedaldi** [comment]
Hi,

could you consider moving this question to the discussion group instead of the issue tracker (see homepage)?

A short answer:

- The classifier would work for any dataset with the given identities (provided that faces are properly cropped, e.g. using the detector — see the main VGG-face project page)

- The features can be used for any face task (just cut the last couple of layer of the network as you would do for e.g. AlexNet)

**Comment by apprisi** [comment]
Thank you for your help. 
I will use discussion group next time.
