### ISSUE TITLE
What's the difference between "number of feature channels" and "number o filters in the bank"?

### ISSUE THREAD

**Issue by zwx8981** [vlfeat/matconvnet#457]
I see the description of vl_nnconv() in the vl_nnconv.m, I was confused with these two concepts.

Y = VL_NNCONV(X, F, B)

%   F is a SINGLE array of dimension FW x FH x FD x K where (FH,FW)
%   are the filter height and width and K the number o filters in the
%   bank. D is the depth of each filter and must match the depth D of
%   X. Alternatively, FD can *divide* the depth D; in this case,
%   filters are assumed to form G=D/FD *groups* of equal size (where
%   G must divide K). Each group of filters works on a consecutive
%   subset of feature channels of the input array X.

 I thought the number of filters means the number of types of filters, equivalent to the number of feature channels. Cause different feature maps are essentially generated by different filters, right? But for  this section ,I am stunned, need help to figure these concepts out in my brain, thank you!

**Comment by fengyunxiaozi** [comment]
I think the "number of feature channels" equal to the "number of filters in the bank". But the concepts "feature channel" and "filter bank" are a bit different. "feature channel" means "feature map" (the convolutional result after ReLU), while "filters" mean the learned weights (without ReLU). 

This is just my own opinion. Hope it helpful for you!!

**Comment by zwx8981** [comment]
@fengyunxiaozi  Thank you for your reply. I load the vgg-m model to see its data structure. And the size of the filters of  first convolution layer is 7*7*3*96, the 7*7 is the size of a filter and the 96 means there are 96 different kinds of filters, right? But I am still confused with the '3', what this means?

**Comment by fengyunxiaozi** [comment]
@zwx8981  the input image usually has 3-bands (RGB). So the filters of the first convolutional layers has three dimensions. Each dimension of the filter operate convolution with one band of the image...

**Comment by zwx8981** [comment]
@fengyunxiaozi Then it will generate 3*96 feature maps, and in the second convolution layer, the size is 5*5*96*256, so the 96 bands in 2nd conv layer are generated by some  links from 3*96 feature maps. The "96" in 2nd conv layer is a hand-crafted number, not like the "3" in first layer, which seems a more natural choice, is that make sense?

**Comment by albanie** [comment]
The *number of feature channels* and the *number of filters* refer to different things.

Suppose `X` is an input with size `W x H x D x N` (where `N` is the size of the batch) to a convolutional layer containing filters `F` (with size  `FW x FH x FD x K`)  in a network . 

* The *number of feature channels* `D` is the third dimension of the input `X` here (for example, this is typically `3` at the first input to the network if the input consists of colour images). 
* The *number of filters* `K` is the fourth dimension of `F`.

The two concepts are closely linked because if the *number of filters* in a layer is `K`, it produces an **output** with `K` feature channels. So the input to the **next** layer will have `K` feature channels.

There is a detailed explanation in Section 4.1 of the [manual](http://www.vlfeat.org/matconvnet/matconvnet-manual.pdf).
