### ISSUE TITLE
Optimization for vl_nnloss.m

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#46]
Hi,

Does anyone has an idea of how to optimize the vl_nnloss layer? I've built a net work for semantic segmentation (output of size 128x128 with 100 as batchsize). But the current version can only process 25 images per sec (on K40c), which is very slow. In fact, the vl_nnloss is the most time-consuming part (90+%), since one has to compare the predicted per-pixel map with groundtruth. I am trying to optimize the current version.

**Comment by lenck** [comment]
Hi, 
have you tried to profile it to see what takes the most of the time? (e.g. described [here](http://uk.mathworks.com/help/matlab/matlab_prog/profiling-for-improving-performance.html))

The 128x128 sized output is quite big and it means that each time it has to create new (presumably GPU) variable `c_` on line 46 with ~1.6M elements so this may cause the biggest overhead...
If the creation of a new variable would be the biggest bottleneck, then probably creating a new custom layer which would take as argument list of indicies `c_` instead of the class labels maybe a solution. If the indexing would be the problem (e.g. that matlab is not able to effectively serialise line 58) then probably writing custom kernel for that may be the way to go...
