### ISSUE TITLE
Error in filters groups

### ISSUE THREAD

**Issue by josave** [vlfeat/matconvnet#50]
Hi,
I am doing binary classification for grayscale images 256x256 size, their structure being mostly small objects (cancer mammograms) in a empty background.  For first layer I choose convolutional with 32 filters of 4x4 size but I get an error:

Error using vl_nnconv The number of filter groups does not divide the total number of filters.

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Maybe the vl_nnconv has some implementation details. Any help will be kindly appreciated. Thanks.

**Comment by josave** [comment]
Solved, recompiling vl_convnet.cu with verbosity=1 and I clearly saw a mistake in my network definition... Great toolbox!

**Comment by lenck** [comment]
Hi, great to hear that you found the solution :)
The 'filter groups' are a feature which is implemented in order to be able to use the original Krizhevsky's ILSVRC classification network - it basically allows you to do a model-based paralelism, as you can divide network into several parts...
And it is used when number of features is divisible by the 3rd dimension of the filter (e.g. output feature map is H x W x C x N and the filters are U x V x C/k x M) then the M filters are divided into k groups where each group uses a C/k portion of the features... So I guess that was the reason of the error, that the third dimension of the filter size was not the size of the feature map...
Just if somebody would be wondering why the error is about 'filter groups' instead of bad dimensionality of the filters :)
