### ISSUE TITLE
Critical bug with instanceWeights in vl_nnloss in beta19

### ISSUE THREAD

**Issue by nightrome** [vlfeat/matconvnet#523]
I have just come across a newly introduced bug with terrible consequences (~beta19). In line 183 of vl_nnloss [1] you check whether instanceWeights are empty, but otherwise you don't do anything.  Therefore opts.instanceWeights are not applied. Using matconvnet-fcn this means that the loss is 1e5 times higher and we face exploding gradients immediately.

[1] https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_nnloss.m#L183

**Comment by ashafaei** [comment]
Yeah, I confirm the existence of this bug too. Had to fix it manually.

Instead of
```matlab
if ~isempty(opts.instanceWeights)
  % important: this code needs to broadcast opts.instanceWeights to
  % an array of the same size as c
  if isempty(instanceWeights)
    instanceWeights = bsxfun(@times, onesLike(c), opts.instanceWeights) ;
  end
end
```

It should say
```matlab
if ~isempty(opts.instanceWeights)
  % important: this code needs to broadcast opts.instanceWeights to
  % an array of the same size as c
  if isempty(instanceWeights)
    instanceWeights = bsxfun(@times, onesLike(c), opts.instanceWeights) ;
  else
    instanceWeights = bxsfun(@times, instanceWeights, opts.instanceWeights);
  end
end
```

I believe the `instanceWeights` at that point is used for cancelling the classes that we don't care about, therefore the current matrix needs to be multiplied by the weights that are provided in opts.

**Comment by nightrome** [comment]
Yes, actually my initial post was a bit misleading. @ashafaei 's solution seems to be correct.

**Comment by lenck** [comment]
Hi, thanks for reporting it, especially to @ashafaei for the proposed fix! :)
Sorry for the bug, I think I've introduced it when I was optimizing the loss function speed. It did not influence the test cases as the `instanceWeights` parameter was ignored in both forward and backward pass. Now it should be fixed in the master branch and the next release...
