### ISSUE TITLE
Any plan of Faster RCNN ?

### ISSUE THREAD

**Issue by zwx8981** [vlfeat/matconvnet#721]
beta23 released a fast-rcnn demo and corresponding model, which is a milestone, i.e. matconvnet begins to support object detection domain. Is there any plan to further support Faster RCNN in the future?

**Comment by albanie** [comment]
Yes, there are plans to support Faster RCNN, along with other object detectors.

**Comment by zwx8981** [comment]
@albanie  Great!

**Comment by lyltencent** [comment]
Hi @albanie , 
I am just wondering if there is an implementation for Faster R-CNN with MATCONVNET available. 
Thank you.

**Comment by OluwoleOyetoke** [comment]
I have the same question, I am trying to implement faster RCNN with MatConvNet. Do you know if MatConvNet has started supporting this yet?  @zwx8981

**Comment by zwx8981** [comment]
@OluwoleOyetoke To the best of my knowledge, not yet. However, Matlab 2017a has just merged faster-rcnn, you may try it...

**Comment by albanie** [comment]
Hi all, sorry that this took so long.  I've added a matconvnet implementation of Faster R-CNN here: https://github.com/albanie/mcnFasterRCNN

**Comment by zwx8981** [comment]
@albanie Great work ! Thank you for the contribution.

**Comment by wajahat57** [comment]
@albanie 
Thanks a lot for your contribution.
How can we train our own detector?
Can you provide a short tutorial?

**Comment by albanie** [comment]
Hi @wajahat57, I don't have much experience with text detection, but at 32x32 pixels I suspect it might be quite difficult to resolve some of the individual characters?  For example, if I resize something like this:

<img src="https://i.imgur.com/bx0s7gZ.png" alt="original" height="150"/>

to a size of `32x32`, I get this:

<img src="https://imgur.com/upph5XW.png" alt="small" height="150"/>

That aside, one useful feature of Faster R-CNN is that it can run on different sized inputs (up to a certain extent), but it would require some modification of the base architecture.  I would try removing the pooling layers to maintain a reasonable feature map size.  The best thing to do is probably to experiment with a few things and try to see what works. 

Unfortunately it won't be possible to construct the detector in `simplenn`, since the topology of the network is a not a linear chain, so usage of either the `dagnn` or [autonn](https://github.com/vlfeat/autonn) wrappers is required here.

**Comment by wajahat57** [comment]
Thanks.
Can you share a diagram of the architectures (a draft sketch would work) of the Nets combined making the Faster RCNN. 
And how to convert autoNN to DAGNN?
I can deal understand DAGNN somewhat but autoNN is difficult for me to grasp.

**Comment by wajahat57** [comment]
Secondly, There is another paper by the same group, Focal Loss and RetinaNet. If that is implemented in MatConvNet, it will be supercede Faster RCNN.
https://github.com/unsky/focal-loss

I have started a query for it: 
https://github.com/vlfeat/matconvnet/issues/1083

**Comment by wajahat57** [comment]
For 32x32 character, I agree that resizing a whole text image to 32x32 would make it worse.
I was hoping to use individual 32x32 characters in training and testing the models later on larger images.
Is it possible in this training environment? 
A 32x32 character image would be having the bounding box (roi) of the same size.
