### ISSUE TITLE
About implementing new layers with cudnn & matconvnet

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#74]
Hi,

I would like to know if it is possible to extend the current CuDNN implementation?
It seems that they only release functional declaration (cudnn.h).
We would appreciate if anyone share his/her experience.

**Comment by vedaldi** [comment]
Hi, I am not really sure what you mean. CuDNN must be downloaded from NVIDIA. MatConvNet will them be able to link to that. At the moment, CuDNN is supported for convolution and pooling (and only max pooling at that due to a bug in the current CuDNN beta), but convolutions are the bottleneck in almost all CNN architectures, so it is still quite useful.

**Comment by xcyan** [comment]
Hi,

Thanks! I was wondering if it is possible to implement some functions (i.e., average pooling) which are currently not supported by CuDNN.

**Comment by vedaldi** [comment]
Hi, yes, if you link to cuDNN, MatConvNet will fallback to its internal GPU implementations for all the other features. Average pooling is one of them.
