### ISSUE TITLE
Error while computing average: Error using rjpg8c

### ISSUE THREAD

**Issue by drohit92** [vlfeat/matconvnet#91]
I am trying to run the Imagnet example. In the process of finding the average of images, I got an error:

computing average image: processing batch starting with image 76545 ...{Error using rjpg8c
JPEG images with CMYK colorspace are not currently supported.

Error in readjpg (line 11)
    A = rjpg8c(filename);

Error in imread (line 415)
    [X, map] = feval(fmt_s.read, filename, extraArgs{:});

Error in cnn_imagenet_get_batch (line 63)
    imt = imread(images{i}) ;

Error in cnn_imagenet>getBatch (line 81)
im = cnn_imagenet_get_batch(images, opts, ...

Error in cnn_imagenet>@(imdb,batch)getBatch(imdb,batch,opts,numThreads) (line
75)
fn = @(imdb,batch) getBatch(imdb,batch,opts,numThreads) ;

Error in cnn_imagenet (line 52)
    temp = fn(imdb, batch) ;

This looks like a problem with my MATLAB. Any solutions?

Thanks.

**Comment by dteney** [comment]
The best is to preprocess the imagenet data so as to have all images in RGB format.

Otherwise, the If you use the vl_imreadjpeg will read CMYK images fine, but you'd still need to turn them into RGB images in your getbatch function.E.g.

c = makecform('cmyk2srgb'); % Only need to be called once

And then in each iteration of the loop over images:
  if size(imt,3) == 1 % Grayscale image
    imt = cat(3, imt, imt, imt) ;
  elseif size(imt,3) == 4 % CMYK image
    imt(isnan(imt)) = 0;
    imt = single(applycform(double(imt), c) .* 255); % Turn CMYK into RGB image
  end

**Comment by drohit92** [comment]
@dteney thanks for the suggestion.. I willl try and let you know..

**Comment by drohit92** [comment]
@dteney  hi .. sry I was testing and it took sometime. I debugged the program and realised that the problem is in the file cnn_imagneet_get_batch at this point line: 61
% acquire image
  if isempty(im{i})
    imt = imread(images{i}) ;
    imt = single(imt) ; % faster than im2single (and multiplies by 255)
Even before I read the image, I gte the error "Error using rjpg8c JPEG images with CMYK colorspace are not currently supported."

in particular for the image at path: data/imagenet12/images/train/n01739381/n01739381_1309.JPEG

This is the image that is creating the problem. Since I can't even read it using imread, I can't convert it to rgb colorspace.

Any suggestions?

**Comment by drohit92** [comment]
Also on doing iminfo I get this: 

imfinfo('data/imagenet12/images/train/n01739381/n01739381_1309.JPEG')

ans =

           Filename: '/home/ImageNet/ILSVRC2012_img_train/n01739381/n01739381_1309.JPEG'
        FileModDate: '10-Jun-2012 18:43:59'
           FileSize: 600055
             Format: 'jpg'
      FormatVersion: ''
              Width: 362
             Height: 379
           BitDepth: 32
          ColorType: 'CMYK'
    FormatSignature: ''
    NumberOfSamples: 4
       CodingMethod: 'Huffman'
      CodingProcess: 'Sequential'
            Comment: {}
        Orientation: 1
        XResolution: 72
        YResolution: 72
     ResolutionUnit: 'Inch'
           Software: 'Adobe Photoshop CS2 Windows'
           DateTime: '2007:05:03 13:56:29'
      DigitalCamera: [1x1 struct]
      ExifThumbnail: [1x1 struct]

**Comment by vedaldi** [comment]
Hi, from the looks of it, it seems a MATLAB limitation. Note, for speed it would be better to use the supplied vl_imreadjpeg tool instead that MATLAB imread. That may also work in your case.

**Comment by drohit92** [comment]
Hi @vedaldi @dteney  from both your suggestions I have made the following chnages which work for now:

1. I use vl_imreadjpeg to read the batch of images
2. use cmyk2srgb to convert the colorspace

Code snippet: cnn_imagenet_get_batch line: 60

im = vl_imreadjpeg(images,'numThreads', opts.numThreads) ;
c = makecform('cmyk2srgb'); % Only need to be called once

for i=1:numel(images)
  if isempty(im{i})
    imt = im{i};  % can remove this now, redundant
    imt = single(imt) ; % faster than im2single (and multiplies by 255)
  else
    imt = im{i} ;
  end
  if size(imt,3) == 1
    imt = cat(3, imt, imt, imt) ;
  elseif size(imt,3) == 4 % CMYK image
    imt(isnan(imt)) = 0;
    imt = single(applycform(double(imt), c) .* 255); % Turn CMYK into RGB image
  end

The code seems to be runnning well now. I will anyways run the entire thing and let you know.

Thanks for the help.

**Comment by rosenfeldamir** [comment]
Hi @vedaldi  , @drohit92 , @dteney , I've also been struggling with this issue. Unfortunately, none of the suggestions worked for me. In fact, reading the CMYK based images (there are several such images in the dataset) has *silently failed*, even using vl_imreadjpeg.
The image is read as a 4-channel image, and attempting to visualize it, either before or after the colorspace conversion as suggested, resulted in a garbled-looking image with diagonal stripes. Such patterns can often appear when there is some offset error when decoding / displaying an image.

Furthermore, I noticed that although there are only several (around 20) such images in the image-net dataset, the learning seems to fail, with error rates still near 1 after the first epoch. 

I have been able to correct this using ImageMagick's convert -colorspace RGB option and now the training seems to work fine. 

As I did not see issues regarding how this affects training, I suggest that this can be caused by compiling vl_imreadjpeg with different libs which handle reading CMYK images correctly. In this case, I am probably not the only one who encountered this.
Thanks,
-Amir

**Comment by AruniRC** [comment]
Hi @rosenfeldamir,

I can also confirm having the same issues with about 23 images from ImageNet.
Separately converting them from CMYK to RGB using ImageMagic was the only option that worked.
Using Matlab code from various sources to do the conversion all gave the weird striped images you have mentioned.

**Comment by rosenfeldamir** [comment]
@AruniRC - thanks for confirming. Indeed, using an external tool to convert the images to RGB (ImageMagick/IrfanView/GraphicsMagick) was the only option that worked for me too. 
I wonder why this has not been reported by more users, with some possible explanations:
1. They did not try to train ImageNet from scratch
2. They discarded the faulty images and continued with their lives :-)
3. They used a preprocessed version on ImageNet which sometime in the past already did away with this issue.
@vedaldi, @lenck  - do you have a take on this? 

p.s - I did not encounter any YCCK images. Did you?

**Comment by rosenfeldamir** [comment]
@AruniRC , @vedaldi  - 
I found it! The problem is NaN values in the CMYK images. If these are removed as suggested by several users during the conversion to RGB colorspace, the problem *seems* to go away. But this is only an illusion : vl_imreadjpeg reads the images incorrectly and the result, before or after conversion, is garbled. 
If nan values are Discarded, the overall effect during training is small since the gradient on these images is negligible to that of the entire batch or training set. But if they are not treated, the resulting filters become nan-valued as well (I checked). Somehow this does not go all the way up to the final layer (maybe the nan-values are treated later ?), but the resulting classification is the same for all images of the batch. 

Converting these images to RGB using e.g ImageMagick solves the problem. You can try it yourself - look at the images when loaded using vl_imreadjpeg or display them using ImageMagick. I am guessing that many users have been training on a slightly corrupted imagenet dataset without realizing it. 
n01739381_1309.JPEG
n02077923_14822.JPEG
n02447366_23489.JPEG
n02492035_15739.JPEG
n02747177_10752.JPEG
n03018349_4028.JPEG
n03062245_4620.JPEG
n03347037_9675.JPEG
n03467068_12171.JPEG
n03529860_11437.JPEG
n03544143_17228.JPEG
n03633091_5218.JPEG
n03710637_5125.JPEG
n03961711_5286.JPEG
n04033995_2932.JPEG 
n04258138_17003.JPEG
n04264628_27969.JPEG
n04336792_7448.JPEG
n04371774_5854.JPEG
n04596742_4225.JPEG
n07583066_647.JPEG
n13037406_4650.JPEG

**Comment by lenck** [comment]
That actually explains why the training fails. I'm trying to investigate this bug for some time, and it actually seems that the copy of the ILSVRC dataset we are using on our machines has been manually curated so all images are in RGB.

In order to fix it I've pushed 2 patches:
* e15733549f6511c9c17ad7d497167849d6807f45 - gracious failure of `vl_imreadjpeg` in case of CMYK images (which it seems the libjpeg reports as YCCK, contrary to imagemagick's `identify`). Yes, you are right that it was broken because it did not re-align the data to Matlab.
* 7e57a8fda5b643f86034bc223d17cf0e357e1c17 forces the colorspace conversion when calling `convert` in `utils/preprocess-imagenet.sh`.

Fixing `vl_imreadjpeg` to support this colorspace is probably not worth it. It would need to be fixed for all three drivers and furthermore those images seem to be removed from ILSVRC14. And in the current state it should fail on `imread` where it informs the user that the colorspace is not supported by Matlab...

Do you have some other suggestions? Maybe simple script which would fix a given dataset?

**Comment by vedaldi** [comment]
Hi,@AruniRC - thanks for confirming. Indeed, using an external tool to convert the images to RGB (ImageMagick/IrfanView/GraphicsMagick) was the only option that worked for me too. 
I wonder why this has not been reported by more users, with some possible explanations:
1. They did not try to train ImageNet from scratch
2. They discarded the faulty images and continued with their lives :-)
3. They used a preprocessed version on ImageNet which sometime in the past already did away with this issue.
@vedaldi, @lenck  - do you have a take on this?I am afraid that indeed we always use a pre-processed version of ImageNet (obtained used GraphicsMagick) for training purposes, so I would not have spotted such errors. Preprocessing is also much faster in practice (as it resizes the images too) so it is probably a good practice. However, it is annoying that such images cause these issues. vl_imreadjpeg *should* be insensitive to the color space however as it relies on the underlying OS-dependent image library (which I assume would be correct) — and should perform the color space conversion automatically.If it does not, then this is squarely a bug in our implementation of vl_imreadjpeg(). Thanks for pointing out this limitation — which platform gives you grief? Linux?p.s - I did not encounter any YCCK images. Did you? —Reply to this email directly or view it on GitHub.

**Comment by rosenfeldamir** [comment]
@lenck , it seems that the modified preprocessing script will fix the problem. In my case, I actually converted to RGB only the images which were CMYK to begin with because I didn't know if ImageMagick would fail when trying to convert an already RGB image : is the colorspace always defined in the image header? if not, this could cause problems. 

At any rate, perhaps the resizing should be decoupled from the conversion, e.g, provide an option to convert all images to some standard RGB format, and resize only optionally. 

@vedaldi  , I am working on Linux, CentOS.

**Comment by lenck** [comment]
@rosenfeldamir the `-colorspace RGB` seems to work fine with RGB images. AFAIK it is stored in a header (as ImageMagick's `identify -verbose <imname>` reports it). This would allow to write some simple script for Linux.
@vedaldi this issue seems to affect Linux only, libjpeg ignores the requested colorspace conversion and also seems to fail to identify the colorspace correctly (YCCK instead of CMYK). On Windows, GDI+ does seem to give RGB output by default. However I cannot test it on MacOS X. Example CMYK image is e.g. [here](https://www.dropbox.com/s/vyfx4ji1pxur1jr/cmyk.jpg?dl=1)

**Comment by vedaldi** [comment]
Hi, ok, I have investigated the problem. There were two errors:

- imreadjpeg was not requesting libjpeg to convert the pixels to RGB

- notably, CMYK -> RGB is not supported by libjpeg in any case (!)

I will push a patch that, while does not allow to read CMYK using libjpeg, at least should properly print an error message explaining the issue.

**Comment by rosenfeldamir** [comment]
@vedaldi , thanks for checking the issue. Such a patch will cause the getBatch function to fail, wouldn't it ?

**Comment by lenck** [comment]
@rosenfeldamir Yes, it would fail. But it would fail gracefully informing correctly about the error. It is out of our hands to try to fix the `libjpeg` implementations...
Furthermore I think that in the new ILSVRC, those few CMYK images are black-listed. For the ILSVRC12 it is possible to prevent this by preprocessing the images using the `preprocess-imagenet.sh`.

**Comment by khazar1** [comment]
I tried "preprocess-imagenet.sh " on ILSVRC2012 data. Still same error for CMYK images!

**Comment by icyzhang0923** [comment]
@drohit92 Have you solved this problem? I try your method,but it doesn'work~
